all:
	xelatex presentation.tex

publish:
	xelatex presentation.tex
	xelatex presentation.tex # for TOC & references

clean:
	rm -f *.pdf *.aux *.glo *.idx *.log *.toc *.ist *.acn *.acr *.alg *.bbl \
		*.blg *.dvi *.glg *.gls *.ilg *.ind *.lof *.lot *.maf *.mtc *.mtc1 \
		*.out *.synctex.gz *.nav *.snm
